SELECT * FROM NOTICES;

--게시글 목록 조회
SELECT * FROM NOTICES ORDER BY REGDATE DESC;

--현재 공지사항에서 가장 큰 CODE 값을 얻어오시오
SELECT NVL(MAX(TO_NUMBER(CODE))+1, 0)+1 FROM NOTICES; --오라클
SELECT ISNULL(MAX(CAST(CODE AS INT)),0)+1 FROM NoticeFiles;
SELECT MAX(CAST(CODE AS INT))+1 FROM NoticeFiles; --sql

--20개씩 나눈 레코드를 얻어오는 쿼리를 작성하시오.
--1페이지, 2페이지
SELECT * FROM NOTICES ORDER BY REGDATE DESC
--ROWNUM을 이용한 페이지 나누기

SELECT *FROM (SELECT * FROM NOTICES ORDER BY REGDATE DESC) WHERE ROWNUM BETWEEN 1 AND 20

INSERT INTO NOTICES(CODE,TITLE,WRITER,CONTENT,REGDATE,HIT) VALUES('140','DDD','HAHA','HI',SYSDATE,'0')

SELECT * FROM (SELECT ROWNUM NUM, N.* FROM (SELECT NOTICES ORDER BY REGDATE DESC) N) WHERE NUM BETWEEN 3 AND 4

--정렬되거나 다른 목적이 있을때 로우넘버 사용
SELECT (ROW_NUMBER() OVER (ORDER BY REGDATE DESC)) NUM, Notices.* FROM NOTICES;

SELECT N.*FROM (SELECT (ROW_NUMBER() OVER (ORDER BY REGDATE DESC)) NUM, Notices.* FROM NOTICES) N WHERE N.NUM BETWEEN 11 AND 20;
--TONUMBER는 오라클에만 있다. 

SELECT MAX(CODE) FROM NOTICEFILES -->NULL이나옴

--CAST(X AS INT)--->X를 INT형으로 바꿔주세요.

SELECT CAST(CODE AS INT)+1 FROM NoticeFiles;-->Null

SELECT * FROM NOTICEFILES;

--이전글 다음글
SELECT TOP 1 * FROM NOTICES WHERE REGDATE > (SELECT REGDATE FROM NOTICES WHERE CODE='242') ORDER BY REGDATE ASC;

SELECT  TOP 1 * FROM NOTICES WHERE REGDATE < (SELECT REGDATE FROM NOTICES WHERE CODE='242') ORDER BY REGDATE DESC;

SELECT * FROM members;

INSERT INTO MEMBERS(MID, NAME, PWD, NICNAME, GENDER, BIRTH, CELLPHONE, REGDATE) VALUES( 'HARING', 'HAARIM', '123489', '꼬꼬', 'f', '19890325', '01052542483', '20150204');
